language: python
cache: pip

matrix:
    include:
        - python: 2.7
          env: TOXENV=flake8
        - python: 2.7
          env: TOXENV=py27
        - python: 3.4
          env: TOXENV=py34
        - python: 3.5
          env: TOXENV=py35
before_install:
  - pip install coveralls
install:
  - pip install tox
script:
  - tox
after_success:
  - coverage combine .coverage_data
  - coveralls